#!/usr/bin/env bash

set -e -x

echo "==> Building helm chart..."

cd $(dirname $0)/..
source ./version

cd ..
[ -f ${CHART_BUILD_DIR} ] && rm -rf ${CHART_BUILD_DIR}
mkdir -p ${CHART_BUILD_DIR}
cp -rf ${1} ${CHART_BUILD_DIR}/${CHART_NAME}

sed -i -e "s/%VERSION%/${CHART_VERSION}/g" ${CHART_BUILD_DIR}/${CHART_NAME}/Chart.yaml
sed -i -e "s/%APP_VERSION%/${CHART_APP_VERSION}/g" ${CHART_BUILD_DIR}/${CHART_NAME}/Chart.yaml
sed -i -e "s/%APP_VERSION%/${CHART_APP_VERSION}/g" ${CHART_BUILD_DIR}/${CHART_NAME}/values.yaml
