#!/usr/bin/env bash

# Setting helm
HELM_VERSION=v3.4.1
HELM_URL="https://get.helm.sh/helm-${HELM_VERSION}-linux-${ARCH}.tar.gz"
HELM_BIN=$(which helm || echo none)
if [ "${HELM_BIN}" == "none" ] ; then
  export HELM_BIN=/usr/local/bin/helm
  if [ ! -x "${HELM_BIN}" ]; then
    curl -sL ${HELM_URL} | tar -xzf - 
    mv linux-${ARCH}/helm ${HELM_BIN} && rm -rf linux-${ARCH}
    chmod 755 ${HELM_BIN}
  fi
fi