#!/usr/bin/env bash

set -e

echo "==> Indexing helm chart..."

cd $(dirname $0)/../..
mkdir -p build

repo_index=${1}

echo "Getting current index from ${repo_index}"
curl -f -H 'Cache-Control: max-age=0,no-cache' -H 'Host: releases.rancher.com' "https://c.storage.googleapis.com/server-charts/${repo_index}/index.yaml?$(date +%s%N)" -o build/index.yaml

${HELM_BIN} repo index --merge build/index.yaml ./build/chart/${repo_index}
