#!/usr/bin/env bash

set -e

echo "==> Packaging helm chart..."

source $(dirname $0)/helm
cd $(dirname $0)/..
. ./version

mkdir -p ../build/chart/${CHART_REPO}

${HELM_BIN} package -d ../build/chart/${CHART_REPO} ../build/chart/rancher-externalip-webhook

if [[ "${CHART_REPO}" == "dev" ]]; then
    echo "dev repo - skipping index"
else
    echo "updating index ... "
    #./chart/index ${CHART_REPO}
fi
