#!/usr/bin/env bash

set -e

echo "==> Packaging helm chart..."

source $(dirname $0)/helm
cd $(dirname $0)/..
source ./version

cd ..
${HELM_BIN} package -d ${CHART_BUILD_DIR} ${CHART_BUILD_DIR}/${CHART_NAME}
rm -rf build/chart/rancher-externalip-webhook

cd ${CHART_BUILD_DIR}
shasum -a 256 * > ${CHART_NAME}-${CHART_VERSION}-SHA256SUMS

#if [[ "${CHART_REPO}" == "dev" ]]; then
#    echo "dev repo - skipping index"
#else
#    echo "updating index ... "
#    #./chart/index ${CHART_REPO}
#fi
