#!/usr/bin/env bash

set -e

source $(dirname $0)/version

echo "==> Building code binaries version ${VERSION} ..."

cd $(dirname $0)/..
[ -f "build/bin" ] && rm -rf build/bin
mkdir -p build/bin
[ "$(uname)" != "Darwin" ] && LINKFLAGS="-extldflags -static -s"
CGO_ENABLED=0 go build -ldflags "-X main.VERSION=$VERSION $LINKFLAGS" -o build/bin/webhook
