#!/usr/bin/env bash

set -e

source $(dirname $0)/version

echo "==> Building code binaries version ${VERSION} ..."

mkdir -p bin
[ "$(uname)" != "Darwin" ] && LINKFLAGS="-extldflags -static -s"
CGO_ENABLED=0 go build -ldflags "-X main.VERSION=$VERSION $LINKFLAGS" -o bin/webhook
