#!/usr/bin/env bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX="-${ARCH}"
TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev${SUFFIX}
fi

IMAGE=${REPO}/externalip-webhook:${TAG}
cd $(dirname $0)/..
docker build --build-arg ARCH=${ARCH} -t ${IMAGE} .
echo Built ${IMAGE}