#!/usr/bin/env bash

shopt -s extglob

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

GIT_TAG=$(git tag -l --contains HEAD | head -n 1)

if [ -n "$VERSION" ]; then
    VERSION="$VERSION${DIRTY}"
elif [ -n "$GIT_TAG" ]; then
    VERSION="$GIT_TAG${DIRTY}"
else
    COMMIT=$(git rev-parse --short HEAD)
    VERSION="${COMMIT}${DIRTY}"
fi

COMMIT_DATE=$(git --no-pager log -1 --format='%ct')
COMMIT_BRANCH=$(git rev-parse --abbrev-ref HEAD | sed -E 's/[^a-zA-Z0-9]+/-/g')
# Drop the v prefix for Version
VERSION_NO_V=$(echo $VERSION | sed "s/^[v|V]//")
# Set semver format CHART_VERSION
if [[ $VERSION_NO_V =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$ ]]; then
	CHART_VERSION=${VERSION_NO_V}
else 
	CHART_VERSION="0.0.0"
fi
CHART_APP_VERSION="${VERSION}"
if echo ${CHART_APP_VERSION} | grep -q dirty; then
    CHART_APP_VERSION=dev
fi
CHART_NAME="rancher-externalip-webhook"
CHART_BUILD_DIR=build/chart

if [ -z "$ARCH" ]; then
    ARCH=amd64
fi


