#!/usr/bin/env bash

shopt -s extglob

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

GIT_TAG=$(git tag -l --contains HEAD | head -n 1)

if [ -n "$VERSION" ]; then
    VERSION="$VERSION${DIRTY}"
elif [ -n "$GIT_TAG" ]; then
    VERSION="$GIT_TAG${DIRTY}"
else
    COMMIT=$(git rev-parse --short HEAD)
    VERSION="${COMMIT}${DIRTY}"
fi

COMMIT_DATE=$(git --no-pager log -1 --format='%ct')
COMMIT_BRANCH=$(git rev-parse --abbrev-ref HEAD | sed -E 's/[^a-zA-Z0-9]+/-/g')
LAST_TAG=${GIT_TAG:-'v0.0.0'}
# Drop the v prefix for Chart Version
CHART_VERSION="$(echo ${LAST_TAG} | sed -E 's/^v//' | sed -e 's/^\(.\{55\}\).*/\1/')"
CHART_APP_VERSION=${VERSION}
if echo ${CHART_APP_VERSION} | grep -q dirty; then
    CHART_APP_VERSION=dev
fi
CHART_NAME="rancher-externalip-webhook"
CHART_BUILD_DIR=build/chart

if [ -z "$ARCH" ]; then
    ARCH=amd64
fi